### ISSUE TITLE
App usage

### ISSUE THREAD

**Issue by hitesh123456** [gkoskinopoulos/rideonline-release#1]
Hy! Love what you do . Awesome app , can i use this app in my project ? I wanted the checkout feature as same u implemented in this app. It would be awesome if you provide some details on it . Thanks

**Comment by gkoskinopoulos** [comment]
Hello, unfortunately this app is for a customer. I will publish another project with detail in order to use it.

**Comment by hitesh123456** [comment]
gr8 will wait for that
